[package]
name = "av1-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
tracing = { version = "0.1.40", features = ["attributes"] }
tracing-subscriber = "0.3.18"
